# Generated by Django 4.2.13 on 2026-03-24 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(db_index=True, max_length=100)),
                ('fraud_type', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Reviewing', 'Reviewing'), ('Resolved', 'Resolved')], default='Open', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('policy_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Flagged', 'Flagged'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('adjuster', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('holder', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('premium', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('claims_count', models.IntegerField(default=0)),
                ('fraud_score', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policies',
            },
        ),
    ]
