# Generated by Django 4.2.13 on 2026-03-24 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_verified', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('fraud_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
