# Generated by Django 4.2.13 on 2026-03-24 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('annual_income', models.FloatField(default=0)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('past_claims_count', models.IntegerField(default=0)),
                ('past_fraud_flag', models.BooleanField(default=False)),
                ('late_premium_payments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('policy_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=100)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.FloatField(default=0)),
                ('sum_insured', models.FloatField(default=0)),
                ('policy_status', models.CharField(default='Active', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='api.customer')),
            ],
            options={
                'db_table': 'policy_records',
            },
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('claim_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.FloatField(default=0)),
                ('incident_type', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('fraud_status', models.CharField(default='Pending', max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.policyrecord')),
            ],
            options={
                'db_table': 'claim_records',
            },
        ),
    ]
