# Generated by Django 4.2.13 on 2026-03-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_policyrecord_claimrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='annual_income',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='channel',
            field=models.CharField(default='Retail', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='marital_status',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='risk_level',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
