# Generated by Django 4.2.13 on 2026-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_age_appuser_annual_income_appuser_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='claim_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='occupation',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='past_claims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='policy_type',
            field=models.CharField(default='Auto', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sum_insured',
            field=models.FloatField(default=0.0),
        ),
    ]
